# Generated by Django 3.1.3 on 2023-06-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_auto_20230610_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question_id',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='choice',
            name='content',
            field=models.TextField(default='choice', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(default='title', max_length=200),
        ),
    ]
