# Generated by Django 3.1.3 on 2023-06-11 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0008_auto_20230611_0259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_grade',
            new_name='grade',
        ),
    ]
